name: Twitter to Discord

on:
  schedule:
    - cron: '0 9 * * 1,4'  # 毎週月曜日と木曜日の9:00 UTCに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウトリポジトリ
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 依存関係をインストール
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: スクリプトを実行
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python twitter_to_discord.py
